#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

if ! [ -x "$(command -v ffmpeg)" ]; then
  echo 'Installing ffmpeg with all plugins'
  brew install ffmpeg $(brew options ffmpeg | grep -vE '\s' | grep -- '--with-' | tr '\n' ' ')
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

# Install SF Mono
cp /Applications/Utilities/Terminal.app/Contents/Resources/Fonts/* /Library/Fonts/
